### ISSUE TITLE
Null value

### ISSUE THREAD

**Issue by jstoup111** [PolymerElements/paper-slider#100]
Is it possible to have the slider return a null or undefined value if the slider has not been interacted with?

I've got a case where I have a form that I need to keep track of whether a slider has been interacted with and has a value or if there is no value associated with it yet.

**Comment by blasten** [comment]
You can add a `on-track` event listener in the same way the slider does internally to detect user interaction.  https://github.com/PolymerElements/paper-slider/blob/master/paper-slider.html#L328-L330
