### ISSUE TITLE
IE and Edge

### ISSUE THREAD

**Issue by YtnomSnrub** [PolymerElements/paper-slider#101]
(Accidentally posted in the v0.5 paper-slider so let's try this again)

When clicking a paper-slider in IE or Edge browsers, the resize animation for the thumb originates from a corner of the thumb, instead of the center as it should. This behavior can be seen by opening the demo for paper-slider in Edge (https://elements.polymer-project.org/elements/paper-slider?view=demo:demo/index.html&active=paper-slider). Note: the thumb returns to proper position after releasing the mouse button.

**Comment by blasten** [comment]
This issue is confirmed.  My first guess is `transform-origin` although the default is `50% 50%` https://msdn.microsoft.com/en-us/library/jj127313(v=vs.85).aspx. @keanulee
