### ISSUE TITLE
Make clicked knob's size smaller or customizable

### ISSUE THREAD

**Issue by fuqinho** [PolymerElements/paper-slider#103]
When the knob is clicked or dragged, the knob's size looks too big, compared to the sample pictures on Material Design spec.
https://www.google.com/design/spec/components/sliders.html

![](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bx4BSt6jniD7cG5vbFVudGNVRms/components_sliders_continuous4.png)
In this example picture, the knob size looks around 18x18 (if I assume that the focus ring's size on "Focus" row is 32x32).
However, under current implementation, the knob seems to have 32x32.

Is it possible to make it smaller or customizable?

**Comment by blasten** [comment]
yes, this might have had changed in recent days. Thanks for pointing it out.

**Comment by blasten** [comment]
This issue is fixed now in master.
