### ISSUE TITLE
noink doesn't disable ripple for first click

### ISSUE THREAD

**Issue by davidmaxwaterman** [PolymerElements/paper-slider#105]
If I add the noink attribute, I still get a ripple effect for the first click, though I don't subsequent clicks (maybe - it seems like there is a situation where the ripple effect also occurs after the first one).

Any ideas?

**Comment by davidmaxwaterman** [comment]
I've noticed that the ripple appears even without a click if you focus on another window (eg this one), and then switch back to the one with the slider in it. Very odd.

**Comment by ebidel** [comment]
Are ink and focus different things for this element? I actually don't see an ink effect when you play with the demos at https://elements.polymer-project.org/elements/paper-slider?view=demo:demo/index.html&active=paper-slider. I do see focus rings.

IOW, it's unclear with `noink` does for `paper-slider`. The `noink` property is inherited from `paper-inky-focus-behavior`.

**Comment by blasten** [comment]
@ebidel is right. It should only show the focus ring if you navigate to the slider using the keyboard. This is how it's described in the material design spec. Also, there isn't a way to change the color of the focus ring independently from the knob as the color should match `--paper-slider-knob-color`. Why would you need that?

**Comment by davidmaxwaterman** [comment]
There's definitely something odd going on. Using the demo in another tab, and switching back and forth between this tab and the demo using a mouse click, sometimes there is a ring, and sometimes not.

https://drive.google.com/open?id=0B3rVVZ4job1EeWQxSW9CUHBQLWs

**Comment by blasten** [comment]
@davidmaxwaterman yes, that is expected. Try focusing the textarea to respond back on this page and then switch back and forth between this and other tab. You should see how the textarea lights up again.  This behavior allows to see the currently active element (or focused), so the element is keyboard actionable. In material design, the focus state has a ripple given that the default focus ring [1] is disabled.
1. Default focus ring: 
   ![slider](https://cloud.githubusercontent.com/assets/1410613/12159858/fc874618-b49a-11e5-8b8d-170ade1ba3ab.png)
2. Material design spec:
   https://www.google.com/design/spec/components/sliders.html

**Comment by davidmaxwaterman** [comment]
I'm sorry, but I think you didn't notice how it is only _sometimes_ highlighted...that surely can't be expected or intentional under any circumstances.

**Comment by davidmaxwaterman** [comment]
Actually, _something_ always happens, but it doesn't always /settle/ on the same 'highlighted' state. I find it difficult to understand why that would be intended.

**Comment by blasten** [comment]
@davidmaxwaterman btw I moved this issue to https://github.com/PolymerElements/paper-behaviors/issues/63

**Comment by davidmaxwaterman** [comment]
@blasten : when I read https://github.com/PolymerElements/paper-behaviors/issues/63 it doesn't read like it's the same problem at all...
