### ISSUE TITLE
Number of markers is not correct when decimal values are used

### ISSUE THREAD

**Issue by Protoss78** [PolymerElements/paper-slider#114]
I use the paper-slider element to select decimal value ranges. When I configure the paper-slider to show markers and have a value range below 1.0 the number of markers is not calculated correctly and therefore the snap position does not match the marker position.

This sample works fine:
`<paper-slider min="0.0" max="1.0" step="0.1" max-markers="11" editable pin snaps></paper-slider>`
but when I change the maximum value below 1.0 the number of markers is off by one:
`<paper-slider class="slider" min="0.0" max="0.6" step="0.1" max-markers="7" editable pin snaps></paper-slider>
`

Here is JsFiddle Link that demonstrates the situation:
https://jsfiddle.net/r9gz9q9r/4/

Here is a screenshot:
![bildschirmfoto vom 2016-01-28 19-41-13](https://cloud.githubusercontent.com/assets/4738976/12655046/5466db38-c5f7-11e5-8d83-8c1a659447e4.png)

**Comment by keanulee** [comment]
Whoops, I accidentally just pushed to master. @blasten Can you do a quick sanity check and review my commit https://github.com/PolymerElements/paper-slider/commit/5e70cb579c312d47c421ea888a05f67cde47f005
