### ISSUE TITLE
two-way binding : Maximum call stack size exceeded 

### ISSUE THREAD

**Issue by christophe-g** [PolymerElements/paper-slider#116]
``` html
    <paper-slider min="0" step="0.1" max="2" value="{{scale}}"></paper-slider>
    <paper-input type="number" value="{{scale}}"></paper-input>
```

and enter 1.56 in the paper-input. 
C.

**Comment by keanulee** [comment]
Moved this issue to the Polymer repo (referenced above)

**Comment by keanulee** [comment]
Re-opening this issue - @kevinpschaaf suggested a fix in his comment (https://github.com/Polymer/polymer/issues/3399#issuecomment-185896927) which should be implemented in `paper-slider`. My initial thought is to remove the `_validateValue` method in https://github.com/PolymerElements/iron-range-behavior/blob/master/iron-range-behavior.html#L102 and just passing a clamped value to `_calcRatio`, but this needs to be tested.

**Comment by vojta001** [comment]
The issue in Polymer repo Polymer/polymer#3399 has been closed as beeing resolved. Shouldn't be the same done to this one?

**Comment by keanulee** [comment]
Verified that this is no longer an issue.
