### ISSUE TITLE
Paper-slider demo not working properly on iOS devices

### ISSUE THREAD

**Issue by miguelangel** [PolymerElements/paper-slider#118]
Hi!

I was playing with the paper-slider demo in my iPhone 6S with iOS 9.0.2 and Chrome v48.0.2564.87 (the latest release) and, when I try to slide the 'Labelled pins' section, it does not work properly (the pages scrolls to the top of the page).

[This is the url of the demo I am playing with.](https://elements.polymer-project.org/elements/paper-slider?view=demo:demo/index.html&active=paper-slider)

Thanks for the great work!

Miguel Ángel

**Comment by miguelangel** [comment]
Hi all,

Just to let you know that this issue is still open. I just posted the issue in the wrong place and reposted here (closing the previous).

**Comment by keanulee** [comment]
Hi @miguelusque 

This is an issue with the element catalog (see https://github.com/Polymer/polymer-element-catalog/issues/224). The `paper-slider` works on iOS if you load the demo directly (https://elements.polymer-project.org/bower_components/paper-slider/demo/).
