### ISSUE TITLE
Can't style child paper-progress element with custom style properties

### ISSUE THREAD

**Issue by benknight** [PolymerElements/paper-slider#123]
It should be possible to style the paper-progress element inside of paper-slider.

For example, currently it's not possible to set `--paper-progress-container-color`.

**Comment by keanulee** [comment]
Seems like a good place to define a new custom property. Ideally we have `--paper-slider-background-color` and `--paper-slider-bar-color` (as suggested in #122), but that would change existing API. How about creating `--paper-slider-container-color` for now? Can you send a PR?

**Comment by benknight** [comment]
Sure I'll take a crack at it.
