### ISSUE TITLE
Secondary progress style

### ISSUE THREAD

**Issue by radiia** [PolymerElements/paper-slider#124]
Hello,

I'am using for my application a slider with a minimum value defined with secondaryProgress, it's supposed to be red.

Styling secondary progress don't seem to work anymore, even in the example given in Polymer website.

the demo code shows : 

```
#grade {
       --paper-slider-secondary-color: var(--paper-red-a200);
     }
```

And the result is not styled:
<img width="1216" alt="screen shot 2016-03-21 at 16 12 46" src="https://cloud.githubusercontent.com/assets/3583180/13923206/eb6db04a-ef7f-11e5-8cfa-7db6a7d64c2b.png">

Any thoughts?
Thanks

**Comment by keanulee** [comment]
Hi @radiia 

Seems like there hasn't been a release in a while - this was an issue with a previous version of `paper-progress`, but there shouldn't be this issue if you use the latest version now. The elements catalog will be updated soon. Thanks.
