### ISSUE TITLE
How do I use "markers" property? 

### ISSUE THREAD

**Issue by amamh** [PolymerElements/paper-slider#125]
It doesn't do anything for me and the demo doesn't have an example of it. Also, there is no documentation for that property.

I tried

markers="['1','2']"
markers="{'1','2'}"
markers={{test}} // using angular 2, test is of type string[]

How can I use it?

**Comment by keanulee** [comment]
`markers` is a read-only property that is used to generate the markers on the line. You can add markers by setting `max-markers`. See https://github.com/PolymerElements/paper-slider/blob/master/demo/index.html#L85

**Comment by amamh** [comment]
Thanks, I should have noticed that it's read-only.

What if I want to give my own list of values?

**Comment by keanulee** [comment]
That is not supported - you can only set `max-markers`, which will try to place that many evenly-spaced markers (see https://github.com/PolymerElements/paper-slider/blob/master/paper-slider.html#L653).

**Comment by amamh** [comment]
Alright, but I'm looking for some suggestion... how would you go about doing that? I have only about 5 values so maybe I should use a radiogroup
