### ISSUE TITLE
Slider does not work well with decimal numbers

### ISSUE THREAD

**Issue by ben-8409** [PolymerElements/paper-slider#13]
I use the paper slider to select values from -1.0 to +1.0, the default being 0.0 and the step 0.01:

``` html
<paper-slider editable="true" class="red" min="-1.0" max="1.0" step="0.01" value="0.0">
```

While the slider functionality works, i have two appearance issues, illustrated in the screenshot:
1) The slider bar progress bar cannot work with step smaller then 1, so it is either a 0 or 1 (full).
2) When loaded, the "editable" is empty, see the blue slider. As soon as I change the slider, the numbers appear
![paper-slider](https://cloud.githubusercontent.com/assets/305724/8005142/ec01bcdc-0b86-11e5-9021-8734bc745adf.png)

Thanks very much & best regards.

**Comment by blasten** [comment]
fixed in master!
