### ISSUE TITLE
Setting value using bindings doesn't work

### ISSUE THREAD

**Issue by eximius313** [PolymerElements/paper-slider#134]
### Description

Setting value of `value` attribute using bindings doesn't work 
### Expected outcome

```
<template is="dom-bind" id="myTemplate">
    <paper-slider min="0" max="100" value="{{myVal}}"></paper-slider>
  <template>
  <script>
    var template = document.getElementById('myTemplate');
    template.myVal = 40;
  </script>
```

should set slider's value to `40`
### Actual outcome

the value is `0` instead
### Live Demo

https://jsbin.com/licomigivi/1/edit?html,js,console,output
### Steps to reproduce

Try to set `value` attribute using bindings
### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by keanulee** [comment]
@eximius313 In your demo, you didn't close your template tag properly (`/s/<template>/</template>/`)

**Comment by eximius313** [comment]
@keanulee I have corrected the code.
Could you please look at it now?
https://jsbin.com/licomigivi/1/edit?html,js,console,output
The issue is stil valid

**Comment by keanulee** [comment]
@eximius313 I don't see what's wrong - if you inspect the slider, it has a step value of 250 and a max value of 750, which is what your code does:

![image](https://cloud.githubusercontent.com/assets/1319720/15411527/798b5516-1dd5-11e6-9e91-4ec6d5ca49e2.png)

**Comment by eximius313** [comment]
yes, but `myValue` is set to `500` and pin is still at position `0`

**Comment by keanulee** [comment]
You set `myValue` to `500`, but then you set `myMax` to `0`, so `paper-slider` clamps its value to `0` (since `500 > 0`). You then change `myMax` and `myStep`, but you don't change `myValue` after, so `paper-slider`'s `value` stays at `0`. Had you set `myValue` to `500` after you'll see it update.

https://jsbin.com/ratoziceki/edit?html,js,console,output

**Comment by eximius313** [comment]
you're right. Thank you
