### ISSUE TITLE
Pass paper-slider's name to input element

### ISSUE THREAD

**Issue by codekoala** [PolymerElements/paper-slider#14]
The value of a `paper-slider` element is not included in the payload of a form submission. Perhaps the name given to the `paper-slider` could be given to the actual `paper-input` element. It would probably also be good to include a hidden input element with the slider's name and value when the slider is not marked as editable.

**Comment by blasten** [comment]
Please use `paper-slider` in combination with `iron-form` instead of the native `form` to receive the value in the request's body.
