### ISSUE TITLE
Editable slider breaks (call stack exceeded) if an empty string is written to the input field

### ISSUE THREAD

**Issue by teamdandelion** [PolymerElements/paper-slider#144]
### Description

On the demo editable of paper-slider (https://elements.polymer-project.org/elements/paper-slider?view=demo:demo/index.html&active=paper-slider), typing an empty string into the input field breaks the slider and sends an error to console.
### Expected outcome

Typing an empty string or a "." into the slider should not freeze the page, or cause anything to be thrown to console.
### Actual outcome

The page briefly freezes, and a "polymer.html:1541 Uncaught RangeError: Maximum call stack size exceeded" is thrown to console.
### Live Demo

https://elements.polymer-project.org/elements/paper-slider?view=demo:demo/index.html&active=paper-slider
### Steps to reproduce

Go to the sliders with editable input.
Type a "." or empty string into the input field.

**Comment by keanulee** [comment]
@danmane I believe that was an issue with paper-input which has since been fixed, but the element catalog was not up to date. It has been updated now. Thanks!

**Comment by teamdandelion** [comment]
Cool, thanks for the info.
