### ISSUE TITLE
Markers always remain 2px in height after changing the slider's height

### ISSUE THREAD

**Issue by pdille** [PolymerElements/paper-slider#147]
### Description

Increasing the height of the paper-slider element correctly increases it's height but if markers are enabled they remain at 2px. This is because the CSS for the markers is as follows in paper-slider.html and is a hardcoded 2px:

```
  .slider-markers::after,
  .slider-marker::after {
    ...
    width: 2px;
    height: 2px;
    ...
  }
```
### Expected outcome

Increasing the height of the slider should also increase the height of the markers or the ability to override the CSS for these should be made available.
### Actual outcome

The markers remain at 2px and there is no way to override the CSS for them. (well, except using ::shadow or /deep/ which is going away.)
### Steps to reproduce
1. Put a `paper-slider` element in the page.
2. Add max-markers="someNumber" attribute to the element
3. Add CSS to modify the paper-slider height: e.g. --paper-slider-height: 3px
4. Open the page in the browser and note that the paper-slider is indeed 3px in height but the markers are not.
### Browsers Affected

All browsers affected.

**Comment by keanulee** [comment]
@pdille Seems like `.slider-marker::after` should have `height: var(--calculated-paper-slider-height);` instead of 2px. Mind sending a PR?

**Comment by pdille** [comment]
Just did. See https://github.com/PolymerElements/paper-slider/pull/148

Not sure why the Firefox test is failing. Seems unrelated to my change?
