### ISSUE TITLE
Knob not "snapping" to correct value on tapping

### ISSUE THREAD

**Issue by Inrego** [PolymerElements/paper-slider#16]
When tapping on the slider, the knob will go to that location exactly - whereas the slider will fit to a valid value. That will leave a gap between the slider position and the knob position.

Here's a screenshot:

![image](https://cloud.githubusercontent.com/assets/2242329/8020284/52bbca0c-0c73-11e5-8f96-b9076d955a8e.png)

This does not happen if you slide the knob by click and drag - only when tapping somewhere on the progress bar.

This is most noticable when max value is low (try setting it to 2 or 3)

**Comment by blasten** [comment]
fixed in master!
