### ISSUE TITLE
Slider doesn't adjust for RTL

### ISSUE THREAD

**Issue by dschuyler** [PolymerElements/paper-slider#182]
### Description
When using a paper-slider in RTL the slider is not mirrored over as expected.

### Expected outcome

The left to right nature of the control should swap to right to left (so the min value is on the right and the max value is on the left).

### Actual outcome

The control stays LTR even in a RTL locale. (Simply ignores the language direction).

**Comment by keanulee** [comment]
Fixed in https://github.com/PolymerElements/paper-slider/releases/tag/v1.0.15
