### ISSUE TITLE
Paper-slider vertical, mouse drag still horizontal

### ISSUE THREAD

**Issue by mahdiridho** [PolymerElements/paper-slider#189]
I have a problem to work with paper-slider transform. My purpose is to have several paper-slider vertical. They work with css transform, except the mouse drag. The slider still read the horizontal mouse dragging. They can't move in vertical dragging.

Yup, there is one other component s-slider which support to vertical slider. But it doesn't work on Polymer 2. I have tried to install and using, it didn't appear on the page.

Is there any trick to transform the mouse also together with paper-slider? Or maybe any slider component that support to polymer 2 and also vertical slider?

Please, point me to resolved it..

Thank you,
Mahdi

**Comment by keanulee** [comment]
This is because the touch/track handlers are always based on horizontal positions (x-coordinates). We don't support this use case, and it sounds like it should be a different element because it doesn't seem likely for a slider to be dynamically rotated during the lifetime of a page.

**Comment by flatmax** [comment]
Thanks for your work, we like polymer.

Is there a standard way to get a vertical paper-slider for polymer 2.0 ?
Can you recommend any implementations of elements based on paper-slider which allow vertical operation ?

**Comment by keanulee** [comment]
Looks like there's a third-party fork of paper-slider that supports vertical - that might be a good place to start https://www.webcomponents.org/element/StartPolymer/s-slider
