### ISSUE TITLE
decrement and increment function not firing change event.

### ISSUE THREAD

**Issue by vdegenne** [PolymerElements/paper-slider#202]
adding an EventListener `change` on a `paper-slider` element will get called when changing the location of the slider manually using the mouse.
But if I try to customize the behavior, for instance calling the decrement() function after a keyboard responding custom event, this same EventListener is avoided.
Is this implementation intentional, that would be nice to implement this (at least for polymer3.0 ?)

**Comment by keanulee** [comment]
The `change` event is only fired for user events; `value-change` can be used instead for this case https://github.com/PolymerElements/paper-slider/blob/master/paper-slider.html#L797
