### ISSUE TITLE
'step' is not listed in available properties

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [PolymerElements/paper-slider#203]
`step` is a valid property of `<paper-slider>` element, it's metioned in examples, but not listed in available properties: https://webcomponents.org/element/PolymerElements/paper-slider/elements/paper-slider#properties.

**Comment by keanulee** [comment]
`step` is a property from `IronRangeBehavior` (https://github.com/PolymerElements/iron-range-behavior/blob/master/iron-range-behavior.html#L56). @samuelli Do you know why it's not listed on wc.org?

**Comment by samuelli** [comment]
I'll take a look, looks similar to another report I saw recently.

**Comment by samuelli** [comment]
This has been fixed in the latest deployment.

![image](https://user-images.githubusercontent.com/787668/30223673-b6502846-9480-11e7-8df4-6d65cd254791.png)
