### ISSUE TITLE
Element has 2 behaviors with conflicting value property types

### ISSUE THREAD

**Issue by jklein24** [PolymerElements/paper-slider#22]
Iron-form-element has a "value" property with a type of String and iron-range has a "value" property of type Number. These are conflicting and break the compiler when used together. Which value type is expected in this element and how can we handle the conflict?

**Comment by jklein24** [comment]
FWIW, my proposal would be to remove the value property from iron-form-element altogether and have implementations use their own value type. Right now this would simply mean adding a value property to paper-input.

**Comment by blasten** [comment]
Thanks for reporting the issue. What do you think @morethanreal , @notwaldorf ?

**Comment by notwaldorf** [comment]
Blerg. According to the forms [spec](http://www.w3.org/TR/html401/interact/forms.html#form-controls), controls have a `value`, and it's a string, so the `IronFormElementBehaviour` is correct. Maybe `paper-slider` needs to cast it to a string?

/cc @cdata for thoughts too

**Comment by jklein24** [comment]
I think that also means that we'll need to move IronFormElementBehavior to the end of the behaviors array to get the type right. @sjmiles to confirm. I know it may not matter to Polymer at runtime because it will just cast to a string, but would it matter if you were reflecting to an attribute or something? Either way, I know it matters to the compiler.

**Comment by jklein24** [comment]
Sorry, just looked again and realized that IronFormElementBehavior _is_ after IronRangeBehavior, but we assign a number to value, which is why I was getting a type error from the compiler like:

ERROR - assignment to property value of PaperSliderElement
found   : number
required: string
        this.value = this.min;

This means that we just need to make these assignments strings and we're good :-). I'll send a PR.
