### ISSUE TITLE
Is it possible to style elements inside paper-slide ? 

### ISSUE THREAD

**Issue by ebatgerel** [PolymerElements/paper-slider#221]
Hello, I have a question when i style elements inside `paper-slider` its not accepting css. Is it possible to style elements ? 
Here is my slide example.

![ps](https://user-images.githubusercontent.com/16677052/42304498-1558d454-8059-11e8-8626-b75b892cf40a.PNG)

above image looks three div inside in paper slide and how to style it ?

**Comment by keanulee** [comment]
I don't know why there's those first 3 `<div>`s in `<paper-slider>`'s shadow root (it's not in the provided template), but shadow roots scope CSS styles so you would need to either use a `<style>` tag inside the shadow root or use inline `style` attribute on those `<div>`s.
