### ISSUE TITLE
v.2.0.8 is missing paper-slider.html

### ISSUE THREAD

**Issue by jaichandra** [PolymerElements/paper-slider#228]
### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by keanulee** [comment]
I don't think 2.0.8 should have been tagged - it points to a 3.x commit. @e111077 is deleting the tag enough for bower (it wouldn't have been published on NPM)?

**Comment by e111077** [comment]
That was a mistake. Will rerelease 2.x as 2.0.9

**Comment by e111077** [comment]
Should be fixed in 2.0.9. Sorry about that
