### ISSUE TITLE
input doesn't work in editable mode

### ISSUE THREAD

**Issue by frankiefu** [PolymerElements/paper-slider#3]
Dragging the slider should update the input and vice versa.  But currently it doesn't work.  

![screen shot 2015-05-21 at 5 53 44 pm](https://cloud.githubusercontent.com/assets/116360/7761987/792c5834-ffe2-11e4-9921-d2ece635fb14.png)

**Comment by frankiefu** [comment]
Could be related to https://github.com/PolymerElements/paper-input/issues/36

**Comment by notwaldorf** [comment]
Yeah, I'm pretty sure it's PolymerElements/paper-input#36 as well.

**Comment by frankiefu** [comment]
Fixed by https://github.com/PolymerElements/paper-input/issues/36
