### ISSUE TITLE
paper-slider pin problem

### ISSUE THREAD

**Issue by tdesc** [PolymerElements/paper-slider#33]
Hello,

Having problems using slider with pin.
1. Moving pin to zero = pin disappeared, slider becomes unusable
2. Unable to style slider.

What I get.
http://monosnap.com/image/DEvy9ArFjhLo0qqDSyDZJkILfzqGSb
What I want.
http://monosnap.com/image/cNb6vHglBhAd14CStdaNrMpFBwEDfr

Any plans to improve it? What I want version was working fine in version 0.5.5

**Comment by tdesc** [comment]
To fix problem numer 1. commented line 432.
 _getClassNames: function() {
      var classes = {};
.......
//      classes.ring = this.immediateValue <= this.min;
}
To fix problem number 2.
I need to set #sliderBar { padding: 0; margin:0} don't know how to do it from outside.

**Comment by blasten** [comment]
@tdesc 

> 1. Moving pin to zero = pin disappeared, slider becomes unusable

What browser did you use?  e.g. http://blasten.github.io/elements/paper-slider/demo/?code=1  if you go to the last slider and change the value to zero, the pin remains there & the slider is still functional.

> 1. Unable to style slider.

`paper-slider` has custom properties available for styling. e.g.

``` css
   paper-slider.green {
      --paper-slider-active-color: green;
    }
```

Don't forget to add  `class="green"` to`paper-slider`

Finally, check out https://github.com/PolymerElements/paper-slider#styling-slider for the list of custom properties.

**Comment by tdesc** [comment]
1. MacOS Chrome browser. It seems to have css .ring class problem on my environment.
2. to style slider     
        ::content paper-slider > * > * > #sliderBar.paper-slider
        {
            padding: 0;
            margin: 0;
        }

**Comment by tdesc** [comment]
Problem with displaying slider ( as on screenshots above ) still exists.
set padding and margin to zero, is a wrong way, since slider becomes too narrow and unusable on mobile.
Difference with working demo ( it works just fine, same browser ) 
#activeProgress and #secondaryProgress height is zero ( in demo height: ~2px).

**Comment by tdesc** [comment]
I don't understand why, but replacing height:100% to height: 2px works...
 ::content paper-slider > \* > \* > \* > #progressContainer.paper-progress
        {
            height: 2px;
        }
