### ISSUE TITLE
paper-slider not redrawn when disabled data bound attribute is updated

### ISSUE THREAD

**Issue by vadimgo** [PolymerElements/paper-slider#34]
Use a paper slider in a custom element similar to the following:

``` html
        <paper-slider
            id='progressBar'
            disabled="[[!canSeek]]"
            hidden="[[!isValidDuration(duration)]]"
            on-change="onSliderChange"
            min="0" max="100"
            value="[[getCurrentTime(currentTime)]]"></paper-slider>
```

When the canSeek property is updated, the slider is not redrawn.  However, if following that the value is updated, the slider is drawn in the correct state.  Also, if it is enabled, but is drawn disabled, the end-user can interact with it, at which point it redraws in the correct state.

**Comment by blasten** [comment]
@vadimgo I tested using the following code:

``` html
  <dom-module id="test-app">
    <template>
      <paper-slider value="{{value}}" disabled="[[!ink]]"></paper-slider>
    </template>
  </dom-module>

  <script>
    Polymer({
      is: 'test-app',
      properties: {
        value: {
          type: Number,
          value: 1
        },
        ink: {
          type: Boolean,
          value: true
        }
      }
    });
  </script>

  <test-app></test-app>
```

`document.querySelector('test-app').ink = false` will disable the slider.

**Comment by vadimgo** [comment]
@blasten In your example, change "value: 1" to "value: 0" and then it reproduces, i.e.

document.querySelector('test-app').ink = false
document.querySelector('test-app').ink = true

do not cause the paper-slider to redraw.

**Comment by blasten** [comment]
@vadimgo 

It works in Chrome 43.0.2357.130: 
![slider](https://cloud.githubusercontent.com/assets/1410613/8342483/3a700f64-1a81-11e5-90a6-7f714a83a9cc.png)

 What browser are you using?

**Comment by vadimgo** [comment]
@blasten It doesn't really work - the slider is drawn with disabled colors.

You're right - the slider is actually redrawn (with a larger thumb like it's enabled) but the disabled color scheme is used.

**Comment by vadimgo** [comment]
I understand now - when the value is 0, the grey color scheme is used, so it kind of looks disabled.  Thank you for looking into it, I agree it's working as intended.

**Comment by blasten** [comment]
good to know. :+1:
