### ISSUE TITLE
vertical slider

### ISSUE THREAD

**Issue by NicolasRannou** [PolymerElements/paper-slider#35]
Hi,

Is there any way to do vertical sliders at the moment?

If not, is there any plan to do it?  (not sure the specs say anything about the orientation of the slider)

Thanks!

**Comment by blasten** [comment]
@NicolasRannou No, the spec doesn't mention vertical sliders as far as I know.  ref https://www.google.com/design/spec/components/sliders.html

**Comment by mahdiridho** [comment]
Tyr this library :

https://www.npmjs.com/package/v-paper-slider
