### ISSUE TITLE
how to handle 'immediate-value-change' event

### ISSUE THREAD

**Issue by tdesc** [PolymerElements/paper-slider#36]
Hello, 
I need help in handling 'immediate-value-change' event and value.
I can successfully handle {{value}} when it changes, but not 'immediate' one.

Thanks in advance,
Valentin

**Comment by blasten** [comment]
@tdesc you need to read the immediate value using  the `immediateValue` property when `immediate-value-change` is triggered.

**Comment by tdesc** [comment]
Thanks for help! 
listeners:
        {
            'immediate-value-change': '_immediateCommonVolumeChanged'
        },
