### ISSUE TITLE
[1.0] Typo(s) in docs

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/paper-slider#4]
The description is the same as the `dragging` property. I see the property is `transiting`, but is that a typo?

![screen shot 2015-05-21 at 6 52 48 pm](https://cloud.githubusercontent.com/assets/238208/7762518/9e971c28-ffea-11e4-9551-2b1c45c81e85.png)

**Comment by blasten** [comment]
This is a private property inherited from 0.5. I have removed the description in https://github.com/PolymerElements/paper-slider/pull/5, so it shouldn't show up in the docs.
