### ISSUE TITLE
event.detail.sourceEvent.preventDefault(); cause error if source event is Touch

### ISSUE THREAD

**Issue by suryagaddipati** [PolymerElements/paper-slider#41]
https://github.com/PolymerElements/paper-slider/blob/786197f5986a54b633f8da22ecb7bf8bc4a43df2/paper-slider.html#L379 

that line causes an error on touch devices.

**Comment by blasten** [comment]
@suryagaddipati what error do you see?

**Comment by suryagaddipati** [comment]
oh sorry, missed that part. 

`Uncaught TypeError: event.detail.sourceEvent.preventDefault is not a function`

This is on  Chrome  `Version 43.0.2357.124 (64-bit)`  on OSX

https://developer.mozilla.org/en-US/docs/Web/API/Touch

**Comment by suryagaddipati** [comment]
That fixed it. Thanks for the quick response.

**Comment by blasten** [comment]
:)
