### ISSUE TITLE
Arrow-key press invokes two steps movement

### ISSUE THREAD

**Issue by naoak** [PolymerElements/paper-slider#44]
It seems that an arrow-key press invokes key events twice and results in two steps movement. This issue can be reproduced in any browsers on OS X.

![20150710-025114_capture](https://cloud.githubusercontent.com/assets/1264530/8602708/c2c74542-26ae-11e5-816c-a3fea57507ce.gif)

**Comment by blasten** [comment]
@naoak this is now fixed in master.

**Comment by naoak** [comment]
Thank you for letting me know. It works!
