### ISSUE TITLE
Editable does not work if Polymer.dom='shadow'

### ISSUE THREAD

**Issue by dballesteros7** [PolymerElements/paper-slider#54]
Tried it both in FF 39 and Chrome 45. If Polymer is using full shadow dom then the paper-slider editable input does not work as expected.

If a value is typed into the input box and then Enter is pressed or focus is changed the slider does not react as it usually does in ShadyDom mode. However, changing the slider does change the value in the input box in full ShadowDom mode.

Example:

``` html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title></title>
  <script src="webcomponents-lite.js"></script> <!-- Tried both -lite and full. -->
  <link rel="import" href="paper-slider/paper-slider.html">
</head>
<body>
  <paper-slider editable min="0" max="200" snaps="true" step="5"></paper-slider>
</body>
</html>
```

**Comment by dballesteros7** [comment]
After some search and debugging, I found the reason for this:

http://w3c.github.io/webcomponents/spec/shadow/#events-that-are-not-leaked-into-ancestor-trees

The on-change listener in the paper-input inside the paper-slider won't trigger because the input element is inside the shadowRoot.

Here's an example path of the event when ShadowDom is enabled:

```
0: input#input
1: content
2: div.input-content.label-is-floating
3: document-fragment
4: paper-input-container
5: document-fragment
```

Shouldn't shadyDom also encapsulate events in the same way?

**Comment by blasten** [comment]
This issue is confirmed.

**Comment by blasten** [comment]
Fixed via https://github.com/PolymerElements/paper-input/pull/168
