### ISSUE TITLE
Visual state broken after toggling `disabled` prop from true to false

### ISSUE THREAD

**Issue by benknight** [PolymerElements/paper-slider#57]
Steps to repro:
1. Visit the demo: https://elements.polymer-project.org/elements/paper-slider?view=demo:demo/index.html
2. Highlight the disabled slider example and set the `disabled` property to `false`, e.g. `$0.disabled = false`

**Expected result**: The slider now appears in its default state, with the knob and left progress bar colored blue.

**Actual result**: The section to the left of the knob is still gray as it was when it was disabled.  (Note that this is the case even when the progress slider's `value` is non-zero.

<img width="417" alt="screen_shot_2015-08-30_at_07 12 11_pm_1x" src="https://cloud.githubusercontent.com/assets/786691/9570947/0d8f14dc-4f4b-11e5-9a0d-50a1fe1970f4.png">

**Comment by blasten** [comment]
That's an issue. Thanks for reporting.

**Comment by blasten** [comment]
This is now fixed in https://github.com/PolymerElements/paper-slider/releases/tag/v1.0.6

**Comment by benknight** [comment]
Thanks! Works like a dream. :palm_tree: :palm_tree:
