### ISSUE TITLE
Request: support rotated slider.

### ISSUE THREAD

**Issue by devinivy** [PolymerElements/paper-slider#59]
The slider only responds to tracking in the X direction, where it would be nice if it responded to tracking in the direction of the slider if it's rotated.  The extreme example of this is when the slider is vertical, and you cannot drag the knob in any meaningful manner.  Would this feature be a possibility?

**Comment by devinivy** [comment]
If a PR is welcome, I do have a patch for this.

**Comment by blasten** [comment]
Material design doesn't have vertical sliders. https://www.google.com/design/spec/components/sliders.html#sliders-discrete-slider 

This could be a feature for a generic toolbar, but feel free to fork this repo and add the vertical behavior.
