### ISSUE TITLE
Set `immediateValue` to `notify: true`

### ISSUE THREAD

**Issue by brendankenny** [PolymerElements/paper-slider#60]
This is somewhat related to #32, but this is just to be able to bind to `immediateValue` to make an immediate change in other elements without leaving declarative code. As it is, you have to bind to `value`, which only updates when the user finishes dragging the knob.

**Comment by ebidel** [comment]
@blasten @frankiefu wdyt? I used to bind to this prop in paper-slider 0.5. We need this for the Polymer summit

**Comment by samccone** [comment]
seems quite useful to me :+1:

**Comment by blasten** [comment]
@ebidel sounds good :+1:

**Comment by blasten** [comment]
Shipped in https://github.com/PolymerElements/paper-slider/releases/tag/v1.0.6

**Comment by brendankenny** [comment]
awesome, thanks!
