### ISSUE TITLE
odd stepping behaves...."oddly"

### ISSUE THREAD

**Issue by mvpmvh** [PolymerElements/paper-slider#70]
`<paper-slider min="1" max="7" value="3" step="2" pin snaps></paper-slider>`

I would expect that my slider values would snap 1, 3, 5, 7 but that is not the case. Slider starts at 2 and cannot ever reach 1. The snap indicators is not where the knob snaps to. The final snap value shows '8' in the knob, but the actual value is 7.

**Comment by blasten** [comment]
@mvpmvh this issue has been fixed via https://github.com/PolymerElements/iron-range-behavior/commit/f5d8a686ec541e987041a56ba931a9b1cd93b88a.   

`bower update`
