### ISSUE TITLE
Two Way Slider

### ISSUE THREAD

**Issue by kishaningithub** [PolymerElements/paper-slider#74]
It would be nice if this was a two way slider i.e. a range that the user can move the Min and Max Pin and it has two outputs and not just one.

Use Case:
   -> Filter by "Price Range" in a shopping cart.

Some implementations
   -> https://github.com/ewgenius/paper-interval-slider

I would be nice if polymer had this in its paper element set

**Comment by NicolasRannou** [comment]
Not in the specs so unlikely to be supported until then:
https://www.google.com/design/spec/components/sliders.html

It would also be useful for medical imaging, along with vertical sliders.

Few months ago I played a bit with it: 
http://nicolasrannou.github.io/paper-rangeslider/paper-rangeslider/demo/

But was waiting for the range slider to get more mature before going further...

**Comment by samccone** [comment]
ref: 
https://jqueryui.com/slider/#range

**Comment by blasten** [comment]
related: https://github.com/PolymerElements/paper-slider/issues/8

As @nicolasgarnier pointed out, it's unlikely that `paper-slider` will support a two way slider as it's not in the spec. Also, good to know that there's  a `<paper-rangeslider>`. It just needs to correct the progress bar as it seems to be off a few pixels.

**Comment by samccone** [comment]
> as it's not in the spec

So to me, a range slider is a very common and useful UI component / pattern that plenty of apps use. Are we taking the approach that just because the spec does not explicitly define a component (or in this case a permutation of a component) we do not want to support/make it?

**Comment by blasten** [comment]
@samccone paper-\* elements are specifically for material design elements. We could have an `iron-range-slider` for example.

**Comment by samccone** [comment]
word :) sounds fair to me

**Comment by blasten** [comment]
:) that'd be a good primitive to have.

**Comment by opus1269** [comment]
Wouldn't having it be an iron element make it more difficult since you couldn't leverage any of the paper features? Say you wanted a shadow or ripple, for example. I was thinking you could have another class of elements (that requires the paper elements) that would be for common material design based components that aren't part of the spec.

**Comment by blasten** [comment]
A quick update on this request. After talking to folks, material design may support range sliders in the upcoming months, so I'm reopening this feature request.

**Comment by NicolasRannou** [comment]
awesome! main challenge is to make is touch devices friendly, that is what I was experimenting with even if my implementation is buggy :)

**Comment by blasten** [comment]
I will close this issue and follow up in https://github.com/PolymerElements/paper-slider/issues/69
