### ISSUE TITLE
secondary-progress demo

### ISSUE THREAD

**Issue by robrez** [PolymerElements/paper-slider#75]
I was a bit thrown off when I saw the term `progress bar` repeated throughout the documentation. The _secondary progress_ custom properties in particular caused me to believe the docs were incorrect.

Then I saw it's because paper-slider contains a paper-progress. Do you think we could add a secondary progress example to the demo?

I was struggling to think of good use-case for secondary-progress; Now I realize that it could be a nice way to indicate a "normal range" or "critical range", etc for a value.

**Comment by blasten** [comment]
+1 that would be useful. Feel free to send a PR for the demo :+1:
