### ISSUE TITLE
Problems w/ slider-height property

### ISSUE THREAD

**Issue by robrez** [PolymerElements/paper-slider#78]
There is a custom property that allows the slider height to be changed, but not one for the knob...

http://codepen.io/robrez/pen/jbmRYQ?editors=100

I'm not sure if it would be better to
- expose one for the knob
- derive knob height based on slider height
- stop exposing slider height
- something else

**Comment by blasten** [comment]
interesting, I think we should fix that. Probably it should be based on the slider height. Less work for developers.

**Comment by robrez** [comment]
:+1:  thanks

**Comment by blasten** [comment]
:+1:
