### ISSUE TITLE
Slider value does not round

### ISSUE THREAD

**Issue by jstoup111** [PolymerElements/paper-slider#79]
Having a case where the slider value is getting set to a long floating point instead of rounding appropriately

```
<paper-slider min="-10" max="10" step="0.1" pin="true"></paper-slider>
```

**Comment by blasten** [comment]
That seems a regression after https://github.com/PolymerElements/iron-range-behavior/commit/d0b939f57039ebe092bf4ab8b363a769f4315bcd.  We should fix that.

**Comment by blasten** [comment]
This issue is now fixed in iron-range-behavior.  You can run `bower update`
